import { AutoMap } from "@automapper/classes";
import { ApiProperty } from "@nestjs/swagger";
import { IsEmail, IsMobilePhone, IsOptional, IsString, Matches } from "class-validator";

export class BaseLoginResponse {
  @ApiProperty({ example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsibmFtZSI6Im9tYXJyYXNteSIsImVtYWlsIjoib21hcnJhc215QGdtYWlsLmNvbSIsIm1vYmlsZU51bWJlciI6IisyMDExMjM5NTQ0NjciLCJsYXN0TG9naW4iOiIyMDIzLTA2LTE3VDEwOjIyOjEzLjcwNloiLCJwYXNzd29yZCI6IiQyYiQxMyRxaHczcW9KVUk4SEwzOGt3MVBzREsucVFYUFFKa0loQVg0QThlc0YvVWJKTnNkbnpGd25KSyIsInNhbHQiOiIkMmIkMTMkcWh3M3FvSlVJOEhMMzhrdzFQc0RLLiIsImp3dFNlcnZpY2UiOm51bGx9LCJ1c2VybmFtZSI6Im9tYXJyYXNteUBnbWFpbC5jb20iLCJpYXQiOjE2ODcwMDYzNjYsImV4cCI6MTY4NzE3OTE2Nn0.XTnpw0VWXoqe2OecBkw7kvOWHO96jFd4leLY96xLfDs" })
  token: string
  @ApiProperty({ example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsibmFtZSI6Im9tYXJyYXNteSIsImVtYWlsIjoib21hcnJhc215QGdtYWlsLmNvbSIsIm1vYmlsZU51bWJlciI6IisyMDExMjM5NTQ0NjciLCJsYXN0TG9naW4iOiIyMDIzLTA2LTE3VDEwOjIyOjEzLjcwNloiLCJwYXNzd29yZCI6IiQyYiQxMyRxaHczcW9KVUk4SEwzOGt3MVBzREsucVFYUFFKa0loQVg0QThlc0YvVWJKTnNkbnpGd25KSyIsInNhbHQiOiIkMmIkMTMkcWh3M3FvSlVJOEhMMzhrdzFQc0RLLiIsImp3dFNlcnZpY2UiOm51bGx9LCJ1c2VybmFtZSI6Im9tYXJyYXNteUBnbWFpbC5jb20iLCJpYXQiOjE2ODcwMDYzNjYsImV4cCI6MTY4NzE3OTE2Nn0.XTnpw0VWXoqe2OecBkw7kvOWHO96jFd4leLY96xLfDs" })
  currentHashedRefreshToken: string
}
