import { ApiProperty } from "@nestjs/swagger";

export class RefreshRequest {
  @ApiProperty({required:true,example:"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOnsibmFtZSI6Im9tYXJyYXNteSIsImVtYWlsIjoib21hcnJhc215QGdtYWlsLmNvbSIsIm1vYmlsZU51bWJlciI6IisyMDExMjM5NTQ0NjciLCJsYXN0TG9naW4iOiIyMDIzLTA2LTE3VDEwOjIyOjEzLjcwNloiLCJwYXNzd29yZCI6IiQyYiQxMyRxaHczcW9KVUk4SEwzOGt3MVBzREsucVFYUFFKa0loQVg0QThlc0YvVWJKTnNkbnpGd25KSyIsInNhbHQiOiIkMmIkMTMkcWh3M3FvSlVJOEhMMzhrdzFQc0RLLiIsImp3dFNlcnZpY2UiOm51bGx9LCJ1c2VybmFtZSI6Im9tYXJyYXNteUBnbWFpbC5jb20iLCJpYXQiOjE2ODcwMDYzNjYsImV4cCI6MTY4NzE3OTE2Nn0.XTnpw0VWXoqe2OecBkw7kvOWHO96jFd4leLY96xLfDs"})
  refresh:string
}
